# Generated by Django 3.0.5 on 2020-05-03 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bsServer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PotentialInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProtectionPotential', models.FloatField(max_length=10)),
            ],
        ),
    ]
