# Generated by Django 3.0.5 on 2020-05-03 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bsServer', '0002_potentialinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='potentialinfo',
            name='lastTime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
